In [1]:
import pandas as pd

# Data Prediction

In [2]:
pd.read_csv("titanic.csv")

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [3]:
df = pd.read_csv("titanic.csv",usecols=["Survived","Pclass","Sex","Age","Fare"])

In [4]:
df1 = pd.get_dummies(df["Sex"])

In [5]:
df2 = pd.concat([df,df1],axis=1)

In [6]:
df2

Survived  Pclass     Sex   Age     Fare  female  male
0           0       3    male  22.0   7.2500       0     1
1           1       1  female  38.0  71.2833       1     0
2           1       3  female  26.0   7.9250       1     0
3           1       1  female  35.0  53.1000       1     0
4           0       3    male  35.0   8.0500       0     1
..        ...     ...     ...   ...      ...     ...   ...
886         0       2    male  27.0  13.0000       0     1
887         1       1  female  19.0  30.0000       1     0
888         0       3  female   NaN  23.4500       1     0
889         1       1    male  26.0  30.0000       0     1
890         0       3    male  32.0   7.7500       0     1

[891 rows x 7 columns]

In [7]:
df2.drop("Sex",axis="columns",inplace=True)

In [8]:
df2

Survived  Pclass   Age     Fare  female  male
0           0       3  22.0   7.2500       0     1
1           1       1  38.0  71.2833       1     0
2           1       3  26.0   7.9250       1     0
3           1       1  35.0  53.1000       1     0
4           0       3  35.0   8.0500       0     1
..        ...     ...   ...      ...     ...   ...
886         0       2  27.0  13.0000       0     1
887         1       1  19.0  30.0000       1     0
888         0       3   NaN  23.4500       1     0
889         1       1  26.0  30.0000       0     1
890         0       3  32.0   7.7500       0     1

[891 rows x 6 columns]

In [9]:
df2["Age"].mean()

29.69911764705882

In [10]:
df2["Fare"].mean()

32.2042079685746

## 

In [11]:
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())

In [12]:
df2

Survived  Pclass        Age     Fare  female  male
0           0       3  22.000000   7.2500       0     1
1           1       1  38.000000  71.2833       1     0
2           1       3  26.000000   7.9250       1     0
3           1       1  35.000000  53.1000       1     0
4           0       3  35.000000   8.0500       0     1
..        ...     ...        ...      ...     ...   ...
886         0       2  27.000000  13.0000       0     1
887         1       1  19.000000  30.0000       1     0
888         0       3  29.699118  23.4500       1     0
889         1       1  26.000000  30.0000       0     1
890         0       3  32.000000   7.7500       0     1

[891 rows x 6 columns]

df2

In [13]:
x=df2.drop("Survived",axis="columns")

In [14]:
y=df2["Survived"]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

In [19]:
model.fit(x_train,y_train)

LinearRegression()

In [20]:
model.predict([[3,36,32,0,1]])

array([0.03952176])

In [21]:
model.score(x_test,y_test)

0.36010402386026075

# Logistic Regression

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=20)

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model = LogisticRegression()

In [25]:
model.fit(x_train,y_train)

LogisticRegression()

In [26]:
model.score(x_test,y_test)

0.8212290502793296

In [27]:
model.predict([[3,36,32,0,1]])

array([0], dtype=int64)

# Decision Tree

In [28]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [29]:
input = df2.drop('Survived',axis='columns')

In [30]:
target = df2['Survived']

In [31]:
model.fit(input, target)

DecisionTreeClassifier()

In [32]:
model.predict([[3,36,32,0,1]])

array([0], dtype=int64)

In [33]:
model.score(input, target)

0.9797979797979798

# Randnom forest

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
model2 = RandomForestClassifier()

In [37]:
model2.fit(x_train,y_train)

RandomForestClassifier()

In [38]:
model.score(x_test,y_test)

0.9776536312849162

In [39]:
model.predict([[3,36,32,0,1]])

array([0], dtype=int64)

# Kfolding

In [40]:
from sklearn.model_selection import cross_val_score

In [42]:
from sklearn.svm import SVC

In [53]:
df = cross_val_score(SVC(),x_test,y_test,cv=4)

In [54]:
df

array([0.71111111, 0.64444444, 0.62222222, 0.65909091])

In [55]:
import numpy as np

In [56]:
np.average(df)

0.6592171717171718

In [57]:
df = cross_val_score(RandomForestClassifier(n_estimators=20),x_test,y_test,cv=4)

In [58]:
np.average(df)

0.7983585858585859

In [59]:
df = cross_val_score(RandomForestClassifier(n_estimators=15),x_test,y_test,cv=10)

In [60]:
np.average(df)

0.7764705882352941

In [61]:
df = cross_val_score(RandomForestClassifier(n_estimators=30),x_test,y_test,cv=10)

In [63]:
np.average(df)

0.8045751633986928